sblib/inc/sblib/eib/bus.h, sblib/inc/sblib/platform.h
The original definition of FLASH_BASE_ADDRESS relies on the assumption that flash start is equal to vector start. This does not work with applications that use the boot loader / updater.
=> Set flash start address to definition of CMSIS CORE

sblib/inc/sblib/mem_mapper.h, sblib/src/mem_mapper.cpp
in Thread http://selfbus.forums3.com/post2721.html#p2721 I described the incompatibility of "getUIntX" and "setUIntX" (the Byte order was not the same for writing and reading)
additinal it was neccessary for me to add a header in mem_mapper.h (otherwise the define FLASH_PAGE_SIZE could not be found)
=> changes at MemMapper (byte order of getUIntX and setUIntX)

sblib/inc/sblib/mem_mapper.h
Wurde bisher übersehen (und hat beim out-cs-bim112 jetzt zu Fehlern geführt).
=> MemMapper.isMapped() nun auch als virtual deklariert.

sblib/inc/sblib/timer.h
Die Funktion fehlte mir, um einen Timer für mehrere Aufgaben nutzen zu können.
=> Extended Timer to reset single flags.

sblib/inc/sblib/platform.h, sblib/src/timer.cpp
loop, in case it's called inside a interrupt service routine
=> fixed issue #24 delay(unsigned int msec) will result in a infinite

sblib/inc/sblib/eib/bcu_base.h, sblib/inc/sblib/utils.h, sblib/src/eib/bcu_base.cpp, sblib/src/utils.cpp
BcuBase.setProgPin also changes fatalErrorPin which can be set by setFatalErrorPin
=> closes #29 fatalError() now blinks by default PIN_PROG

sblib/inc/sblib/utils.h, sblib/src/utils.cpp
from cr_startup_lpc11xx.cpp to rapidly blink the program/fatalError-LED
=> closes #31 sblib now overrides the default HardFault exception handler

sblib/inc/sblib/eib/com_objects.h, sblib/inc/sblib/eib/com_objectsBCU1.h, sblib/inc/sblib/eib/com_objectsSYSTEMB.h, sblib/src/eib/com_objects.cpp, sblib/src/eib/com_objectsBCU1.cpp, sblib/src/eib/com_objectsSYSTEMB.cpp
Add KNX spec reference comments. Turns out that for any object type >20, `ComObjects::telegramObjectSize()` accessed out-of-bounds memory.
Fix:
1. Do not expose the `objectTypeSizes` array via `getObjectTypeSizes()` anymore to prevent out-of-bounds accesses
2. Use result of `objectSize()` function as telegram object size instead
3. Ensure that no out-of-bounds access can happen in `ComObjectsBCU1::objectSize`
4. That also solves the TODO in `ComObjects::_objectWrite`
=> Fix out-of-bounds memory access in SYSTEMB

Bus-Updater/src/decompressor.cpp
Found in my type safety endeavors (will request to merge that in another bigger PR):
`startAddrOfPageToBeFlashed` is an address and `executeProgramFlash` expects an address, so there's no need to dereference the field.
Please note that this is one likely reason why differential mode didn't work, but I did not run a test of the feature with this fix applied, so there may very well be other open issues.
=> Fix incorrect pointer dereference

Bus-Updater/BootloaderLoader/src/app_main.cpp, Bus-Updater/inc/boot_descriptor_block.h, Bus-Updater/inc/decompressor.h, Bus-Updater/inc/dump.h, Bus-Updater/inc/flash.h, Bus-Updater/src/boot_descriptor_block.cpp, Bus-Updater/src/bootloader.cpp, Bus-Updater/src/decompressor.cpp, Bus-Updater/src/flash.cpp, Bus-Updater/src/update.cpp, doc/TypeUsage.md, sblib/inc/sblib/internal/iap.h, sblib/inc/sblib/mem_mapper.h, sblib/inc/sblib/platform.h, sblib/inc/sblib/print.h, sblib/src/i2c.cpp, sblib/src/iap.cpp, sblib/src/mem_mapper.cpp, sblib/src/print.cpp, test/sblib/cpu-emu/system_lpc11xx.c
This renders a bunch of type casts unnecessary and helps to find and fix issues like the one in #53 way earlier.
⚠️ There are a few changes in this PR that are more risky than the stuff I proposed for inclusion previously. ⚠️ 
Especially, the changes to the `IAP_Parameter` data structure as well as the external variables inserted by the linker in Bus-Updater and BootloaderLoader have some very high potential for breakage. I've quadruple-checked everything and did the best I could, but since I'm *still* in the planning stage for my test hardware setup, I did not test this on real hardware. So handle with care.
=> Use pointers for memory addresses

sblib/inc/sblib/platform.h, sblib/inc/sblib/types.h, sblib/inc/sblib/utils.h, test/sblib/src/protocol.cpp
Together with #55, these changes allow me to compile the projects with GCC 12.2 in MSYS2, package mingw-w64-ucrt-x86_64-gcc, with the 64-bit compile target -- and the tests succeed, too! I've extracted them into this separate PR as they are more about compatibility with different C++ language versions and flavors than about memory addressing.
Please see individual commit and code comments for details and reasoning.
=> Improve compiler compatibility

doc/KNX TP1 Bus implementation.md, sblib/inc/sblib/eib/bus.h, sblib/src/eib/bus.cpp
Up to now, the `Bus` class only detected that there was a collision on the bus, and even that not in every case. Then, it stopped sending and let the reception of the frame fail. Improve this in several ways:
1. Run collision detection whenever we're sending high data+parity bits (i.e. for all and not just for some of them)
2. When we detect a collision, switch to RX in a way that allows us to receive and process the collided frame, including correct checksum
3. Ensure repeated telegrams have lower risk of collision by following the KNX spec and sending them after 50 bit time instead of 76 bit time
=> Handle collisions gracefully

sblib/inc/sblib/eib/bus.h, sblib/inc/sblib/eib/bus_debug.h, sblib/src/eib/bus.cpp, sblib/src/eib/bus_debug.cpp
After sending out a telegram, we wait for an acknowledge frame. Previously, when we did not receive an ACK but a real telegram, we did not repeat the telegram anymore.
With this fix, receiving another unrelated telegram does not clear the `repeatTelegram` flag anymore. Also, only the first acknowledge frame we receive within the allotted time window is evaluated. Consecutive ACKs or ACKs sent in response to other telegrams do not prevent our repetition anymore.
=> Ensure telegrams are repeated if necessary

Bus-Updater/.cproject, Bus-Updater/inc/dump.h, Bus-Updater/src/bootloader.cpp
- changed flow so serial output of bus-updater is also send to serial port if it is opend by the sblib
- deleted macro `dumpKNXAddress` cause it was used only once
- new debug build (telegram lvl 1 & 2 disabled) linking against the debug sblib so its easier to debug low level functions of the sblib itself
=> Don't setup serial port, if sblib already did it

Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/bootloader/BootloaderStatistic.java, Bus-Updater/src/bcu_updater.cpp, Bus-Updater/src/update.cpp, sblib/inc/sblib/eib/bus.h, sblib/inc/sblib/eib/knx_tlayer4.h, sblib/src/eib/bus.cpp, sblib/src/eib/knx_tlayer4.cpp, test/lib-test-cases/src/tc_tlayer4_telegram.h
Transport layer 4 is not responsible to check for repeated telegrams
=> Fix TL4 not responsible for repeated check 

sblib/inc/sblib/eib/bus.h, sblib/src/eib/bus.cpp
There is an ugly `noInterrupts()`/`interrupts()` pair in `Bus::sendTelegram`. It disables *all* interrupts while we're checking whether we're in the `IDLE` state and should start sending right away. After analyzing the situation and listing a few options, Approach 4 is implemented in this PR as it is the most reliable one.
```
noInterrupts();
if (state == IDLE)
{
...
}
interrupts();
```
*Problem statement:* Can we do better, ideally without the `noInterrupts`/`interrupts` pair?
```
timer.noInterrupts();
if (state == IDLE)
{
...
}
timer.interrupts();
```
Improves matters. Still, in the time span with disabled interrupts there's no way to detect falling edges (start bits) on the capture channel pin. Thus, we might miss a full telegram.
```
if (state == IDLE)
{
timer.noInterrupts();
if …
```
=> Do not disable interrupts anymore when starting to send

Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/DeviceManagement.java, Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/Updater.java, Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/bootloader/BootDescriptor.java, Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/bootloader/BootloaderStatistic.java, Bus-Updater/src/bcu_updater.cpp, Bus-Updater/src/update.cpp, sblib/inc/sblib/eib/knx_tlayer4.h, sblib/src/eib/bus.cpp, sblib/src/eib/knx_tlayer4.cpp
This PR contains the following changes:
1. PC Updater: Reconnect to device without any delay when the connection drops.
2. PC Updater: Response timeout is 3sec per the KNX spec.
3. sblib: Never send LL_BUSY acknowledge frames. Per the KNX spec, these should only be sent when a device is certain it'll be unable to process the telegram in the next 100ms, otherwise it should just stay silent (and wait for the repeated telegram).
4. sblib: In connection-oriented communication, always send T_ACK in action A03 per the KNX spec.
=> Improve compliance with KNX spec

sblib/src/eib/bus.cpp
Tests have shown that `-O3` does not really help to improve Isr's performance but increase its size by a lot (~1000 bytes)
=> compile Bus Isr with `-Os` to save flash space

Bus-Updater/PC_updater_tool/source/README.md, Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/CliOptions.java, Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/DeviceManagement.java, Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/Mcu.java, Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/Updater.java
The sblib implements the `Transport Layer 4 Style 1 Rationalised` which, together with calimero-core, can cause connection aborts ending in an infinite loop of `T_CONNECT/T_DISCONNECT`. The new cli option `--timeout` prevents this by utilizing the 6s timeout (defined in the transport layer) after a `T_DISCONNECT` to set the bootloader back to a defined state.
=> Add cli option `timeout`

sblib/inc/sblib/eib/bus.h, sblib/src/eib/bus.cpp, test/sblib/src/protocol.cpp
* RX pin must be low for at least 3µs to be regarded as 0 bit (this filters out short spikes)
* On collisions due to spikes, logging of end of stop bit was incorrect
* Collision detection only performed when falling edges are supposed to happen per the bus timing
* Received repeated telegrams must also be LL_ACKed, even if the first/previous repetition was processed correctly
* Sent repeated telegrams must always have the repeated indicator set
=> Improve detection and handling of spikes, and their consequences

Bus-Updater/.cproject, Bus-Updater/BootloaderLoader/.cproject, Bus-Updater/BootloaderLoader/src/app_main.cpp, Bus-Updater/PC_updater_tool/source/README.md, Bus-Updater/PC_updater_tool/source/build.gradle, Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/DeviceManagement.java, Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/ToolInfo.java, Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/Updater.java, Bus-Updater/PC_updater_tool/source/src/main/java/org/selfbus/updater/bootloader/BootloaderIdentity.java, Bus-Updater/inc/version.h, Bus-Updater/src/bootloader.cpp, Bus-Updater/src/update.cpp
This PR enables the PC_Updater_Tool to retrieve and display the sbLibs version of a bus-updater/bootloader with the `UPD_REQUEST_BL_IDENTITY` command
=> Add sblib version to `UPD_RESPONSE_BL_IDENTITY` response

firmware_updater/bootloader/.cproject, firmware_updater/bootloader/src/bootloader.cpp, firmware_updater/bootloaderupdater/.cproject
The GNAX (IO16FM) Board has a different Prog button pin. To build the bootloader for GNAX board, a different build config is neccessary.
=> Add bootloader build config for GNAX board
